name: markdown-transformer CI

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12
            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.8.3
                virtualenvs-create: false
            - name: Install dependencies
              run: poetry install
            - name: Test with pytest
              run: pytest -vvv
